using AutoAIBuilder.Domain.Semantics;

namespace AutoAIBuilder.Domain.Recognition;

public sealed record RecognitionCandidate(
    Guid Id,
    string Handle,
    string ObjectType,
    string SourceLayer,
    string BlockName,
    string TextContent,
    double PositionX,
    double PositionY,
    double PositionZ,
    string CoordinateSystem,
    string PositionSource,
    double SourceInsertionX,
    double SourceInsertionY,
    double SourceInsertionZ,
    double RotationDegrees,
    double ScaleX,
    double ScaleY,
    double ScaleZ,
    SemanticDiscipline? ProposedDiscipline,
    string ProposedCode,
    string ProposedDescription,
    string ProposedLayer,
    string ProposedHeight,
    SemanticConfidence Confidence,
    int ConfidenceScore,
    string DetectionReason,
    RecognitionCandidateStatus Status,
    string? ReviewNote,
    DateTimeOffset? ReviewedAt,
    bool LegendMatched = false,
    string LegendDescription = "",
    string LegendEvidence = "",
    int ExpansionDepth = 0,
    string RootHandle = "",
    string StablePath = "",
    string GeometrySignature = "",
    int PrimitiveCount = 0,
    int NestedInsertCount = 0,
    bool MatchedByGeometryTemplate = false);
